version: '3.7'

services:
  constructor:
    container_name: ui
    build: ./constructor_ui
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  api:
    container_name: api
    build: ./api
    ports:
      - 80:80

  database-new:
    image: mongo:4.0.5
    container_name: database
    environment:
      MONGO_INITDB_DATABASE: mongo_db
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'